#!/usr/bin/env bash
# Build, test and install can-proxyd as a systemd service on a Pi (or any
# systemd Linux). Mirrors qt-cluster-demo/scripts/build-and-deploy.sh.
#
#   ./scripts/deploy.sh --plugin=emu-ev --vehicle-if=vcan1        # bench, emulator on vcan1
#   ./scripts/deploy.sh --plugin=obd2-ice --vehicle-if=can0       # real car on a CANable
#   ./scripts/deploy.sh --plugin=sim                              # no vehicle at all
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-${REPO_ROOT}/build}"
JOBS="${JOBS:-$(nproc)}"
PLUGIN=""
VEHICLE_IF="vcan1"
CONTRACT_IF="vcan0"
BITRATE="500000"
SOURCE=""
SKIP_TESTS=0
SKIP_DEPLOY=0

usage() {
    cat <<USAGE
Usage: $0 --plugin=<sim|obd2-ice|emu-ev|emu-hybrid> [options]

  --plugin=NAME         vehicle plugin to run (required)
  --vehicle-if=IF       vehicle-side interface (default vcan1; canN for a real car)
  --contract-if=IF      contract bus (default vcan0)
  --bitrate=BPS         bitrate for a real canN (default 500000)
  --source=KIND         plugin 'source' argument: emulator|live|replay
                        (default: emulator for vcanN, live for canN)
  --skip-tests          do not run ctest after building
  --skip-deploy         build only; do not write the env file or touch systemd

Environment overrides: BUILD_DIR, JOBS
USAGE
}

for arg in "$@"; do
    case "${arg}" in
        --plugin=*)      PLUGIN="${arg#*=}" ;;
        --vehicle-if=*)  VEHICLE_IF="${arg#*=}" ;;
        --contract-if=*) CONTRACT_IF="${arg#*=}" ;;
        --bitrate=*)     BITRATE="${arg#*=}" ;;
        --source=*)      SOURCE="${arg#*=}" ;;
        --skip-tests)    SKIP_TESTS=1 ;;
        --skip-deploy)   SKIP_DEPLOY=1 ;;
        -h|--help)       usage; exit 0 ;;
        *) echo "Unknown argument: ${arg}" >&2; usage; exit 2 ;;
    esac
done
[[ -n "${PLUGIN}" ]] || { echo "--plugin is required" >&2; usage; exit 2; }
case "${PLUGIN}" in sim|obd2-ice|emu-ev|emu-hybrid) ;; *) echo "unknown plugin ${PLUGIN}" >&2; exit 2 ;; esac
if [[ -z "${SOURCE}" ]]; then
    [[ "${VEHICLE_IF}" == vcan* ]] && SOURCE="emulator" || SOURCE="live"
fi

# ---------------------------------------------------------------- dependencies
missing=()
command -v cmake >/dev/null 2>&1 || missing+=(cmake)
command -v g++ >/dev/null 2>&1 || missing+=(g++)
[[ -e /usr/include/linux/can/isotp.h ]] || missing+=(linux-libc-dev)
if (( ${#missing[@]} )); then
    echo "Missing build dependencies. Install with:" >&2
    echo "  sudo apt-get install -y ${missing[*]}" >&2
    exit 1
fi

# ---------------------------------------------------------------------- build
echo "== Building in ${BUILD_DIR} (${JOBS} jobs)"
cmake -S "${REPO_ROOT}" -B "${BUILD_DIR}" -DCMAKE_BUILD_TYPE=Release >/dev/null
cmake --build "${BUILD_DIR}" -j "${JOBS}"

if (( ! SKIP_TESTS )); then
    echo "== Unit tests"
    # Integration tests (label "integration") need vcan interfaces and own
    # them while running; a chroot image build shares the host's namespace
    # and would collide with a running bench, so only unit tests run here.
    ctest --test-dir "${BUILD_DIR}" --output-on-failure -LE integration
fi

(( SKIP_DEPLOY )) && { echo "Build complete (deploy skipped)."; exit 0; }

# --------------------------------------------------------------------- deploy
ENV_PATH="${REPO_ROOT}/systemd/can-proxyd.env"
if [[ "${REPO_ROOT}" != "/home/pi/car-can-proxy" ]]; then
    echo "WARNING: the systemd units use hard-coded /home/pi/car-can-proxy paths," >&2
    echo "         but this checkout is at ${REPO_ROOT}. Adjust the units before enabling." >&2
fi
extra_args_line="EXTRA_ARGS="
if [[ -f "${ENV_PATH}" ]]; then
    prev="$(grep -E '^EXTRA_ARGS=' "${ENV_PATH}" | tail -1 || true)"
    [[ -n "${prev}" ]] && extra_args_line="${prev}"
fi
plugin_args="--plugin-arg source=${SOURCE}"
[[ "${PLUGIN}" == "sim" ]] && plugin_args=""
cat > "${ENV_PATH}" <<ENVEOF
# Generated by scripts/deploy.sh - re-run it to change plugin or interfaces.
CONTRACT_IF=${CONTRACT_IF}
VEHICLE_IF=${VEHICLE_IF}
VEHICLE_BITRATE=${BITRATE}
PLUGIN=${PLUGIN}
PLUGIN_ARGS=${plugin_args}
# Free-form additions (kept across re-deploys), e.g. --record=/home/pi/session.log
${extra_args_line}
ENVEOF
echo "Wrote ${ENV_PATH}:"
sed 's/^/    /' "${ENV_PATH}"

if ! command -v systemctl >/dev/null 2>&1; then
    echo "systemctl not found - skipping service installation" >&2
    exit 0
fi
echo "== Installing services (sudo required)"
for unit in can-proxy-links can-proxyd; do
    [[ -L /etc/systemd/system/${unit}.service ]] || sudo systemctl enable "${REPO_ROOT}/systemd/${unit}.service"
done
sudo systemctl daemon-reload
sudo systemctl restart can-proxy-links can-proxyd
sleep 1
sudo systemctl --no-pager --lines=5 status can-proxyd || true
echo "Contract on ${CONTRACT_IF}: ${BUILD_DIR}/tools/contract-dump ${CONTRACT_IF}"
